name: build and release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get Version
      run: |
        ./check.sh
        echo "tag=$(cat tag)" >> $GITHUB_ENV

    - name: Build
      if: ${{ env.tag != '0' }}
      run: ./build.sh

    - name: Release
      uses: softprops/action-gh-release@v2
      if: ${{ env.tag != '0' }}
      with:
        tag_name: v${{ env.tag }}
        files: |
          *.deb
          Packages
          Release